### ISSUE TITLE
Hotel booking

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#101]
One flag + One view
Using the flag module, create a flag "I want to book a room in TUNE HOTEL CEBU CITY".
The flag is unique for each user and only for registered users.
Using the views module, create a view as a table to display all the users who used the flag "I want to book a room in TUNE HOTEL CEBU CITY".

**Comment by marychris** [comment]
Where in the site should this be located?

**Comment by Luukyb** [comment]
Thanks @marychris !
