### ISSUE TITLE
Share to social media: META TAGS

### ISSUE THREAD

**Issue by zkanda** [Luukyb/DrupalcampCebu2014#11]
Add meta tag for social media websites.
This makes sure that when the site is shared in facebook, it's gonna have the right content on it..

**Comment by Luukyb** [comment]
Thanks for creating this issue.
Currently, when you post a link with the site URL on facebook, the logo is wrong because it's taking the content from the animated logo we are using. It should be a logo predefined in the metadata.

**Comment by Luukyb** [comment]
Here is an example of the issue : http://imgur.com/J7JCrf2

**Comment by Luukyb** [comment]
We need to implement the metatags from fb. http://davidwalsh.name/facebook-meta-tags

**Comment by johnrosswvsu** [comment]
I will try this out: https://www.drupal.org/project/opengraph_meta

**Comment by mtem27** [comment]
@Luukyb.

Please check. Thanks.

Tere

**Comment by Luukyb** [comment]
Thanks Tere.
Merged.
BTW for your PR title, you need a hashtag otherwise it doesnt appear here. "Facebook Metatag. Ticket #11"
