### ISSUE TITLE
Add new coffee sponsor and adjust theme

### ISSUE THREAD

**Issue by johnrosswvsu** [Luukyb/DrupalcampCebu2014#119]

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check. https://github.com/Luukyb/DrupalcampCebu2014/pull/120

I have temporarily made some changes on the production views. But I have committed these changes on my fork that needs to be merged.

Thanks.

The css needs to be updated but I might not be the best candidate for it. Thanks.

This is how production currently looks. Could you please coordinate with any one good in thumbing to align them? http://screencast.com/t/bW9l79X9Uc

Thanks.

**Comment by Luukyb** [comment]
Cool, thanks for the work @johnrosswvsu !

@marychris could you update the sass / css on monday ? thanks

**Comment by Luukyb** [comment]
Thanks miss!
