### ISSUE TITLE
Default terms in site profile

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#13]
When installing using the install profile we should already have a set of default terms, see wiki.
This can probably be done using features module, then adding the feature to the installation profile info file.

**Comment by johnrosswvsu** [comment]
Working.

**Comment by johnrosswvsu** [comment]
I will include this feature in this PR https://github.com/Luukyb/DrupalcampCebu2014/pull/24

**Comment by johnrosswvsu** [comment]
- Added terms and featured
- Configured in: [url]/admin/config/content/uuid_features
- This issue will go along witht he PR of https://github.com/Luukyb/DrupalcampCebu2014/pull/24

PS: There seems to be no default terms for “Day” vocabulary.

https://github.com/Luukyb/DrupalcampCebu2014/pull/24

**Comment by johnrosswvsu** [comment]
PS: @Luukyb I added "Day 1" and "Day 2" as default terms for Day vocabulary.

**Comment by Luukyb** [comment]
Thanks @johnrosswvsu !
