### ISSUE TITLE
Google controls on venue block

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#17]
We can't use the controls of the google map on the homepage, block "venue".

**Comment by johnrosswvsu** [comment]
Hi @Luukyb 

Fixed css for venue to allow map control. Please check.

https://github.com/Luukyb/DrupalcampCebu2014/pull/30

**Comment by johnrosswvsu** [comment]
I will be adding a page as well.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

I added a configurable venue page as well.

Thanks.

**Comment by johnrosswvsu** [comment]
This needs further styling and content on the venue page.

{url}/venue

Added config for venue page
[url]/admin/config/system/venue

For config of venue block
[url]/admin/structure/block/manage/drupalcebu2014_map/drupalcebu2014_map_text/configure

**Comment by johnrosswvsu** [comment]
@Luukyb please check.

**Comment by Luukyb** [comment]
Could you setup the settings as $conf in the settings.php file ?

**Comment by johnrosswvsu** [comment]
Hi @Luukyb 

Added map content as conf in settings.php

Please note:
Scroll disable is only applicable to GMap API and not on iframe embed. I have make a work around to prevent scrolling on first time.

https://productforums.google.com/forum/#!topic/maps-engine/LKGecdRTubU

Please check.

https://github.com/Luukyb/DrupalcampCebu2014/pull/58

**Comment by Luukyb** [comment]
Merged and fixed, thanks @johnrosswvsu !
