### ISSUE TITLE
Drupal vertical tabs

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#19]
Very bad theming issues on vertical tabs.
Try to edit or create a new node and you can't save it because the vertical tabs are on top of the save button.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

I fixed the css issue on vertical tabs (compass watch.). Please check.

http://github.com/Luukyb/DrupalcampCebu2014/pull/29

**Comment by Luukyb** [comment]
Thanks JR !!!
