### ISSUE TITLE
Content type sponsor

### ISSUE THREAD

**Issue by marychris** [Luukyb/DrupalcampCebu2014#20]
see Wiki for details about the fields.

**Comment by johnrosswvsu** [comment]
Hi @marychris,

I could continue working on this one also.

Thanks.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,
- Created Sponsor content type and featured
- Updated Content session’s description.

https://github.com/Luukyb/DrupalcampCebu2014/pull/24

**Comment by Luukyb** [comment]
Thanks MC & JR. PR merged.
