### ISSUE TITLE
Wysiwyg with images upload

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#21]
We need a Wysiwyg with images upload function.

**Comment by johnrosswvsu** [comment]
Working. (Can't seem to assign to my self.)

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check updates here: https://github.com/Luukyb/DrupalcampCebu2014/pull/22

The description and notes are also in there.

Thanks.

**Comment by Luukyb** [comment]
Thanks @johnrosswvsu !
