### ISSUE TITLE
Sponsors Views

### ISSUE THREAD

**Issue by johnrosswvsu** [Luukyb/DrupalcampCebu2014#27]
Same as with other views

**Comment by johnrosswvsu** [comment]
Updated in https://github.com/Luukyb/DrupalcampCebu2014/pull/28

**Comment by Luukyb** [comment]
Many tpl. Need to review.

**Comment by Luukyb** [comment]
Thanks JR.
@marychris could you redo some of your work ? so we can avoid the tpl files.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb, I removed the tpls for the views. Please check.
