### ISSUE TITLE
Sessions workflow

### ISSUE THREAD

**Issue by johnrosswvsu** [Luukyb/DrupalcampCebu2014#33]
By default, submitted sessions are not published a re are yet to be approved.

Some fields like room and date are only accessible to admins or editor.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check.

Details:
Added workflow for session.
Adding field permissions to day and time
Adding editor and administrator roles.
Adding approval flag for session for admin and editor (flag module included.)

https://github.com/Luukyb/DrupalcampCebu2014/pull/34

**Comment by johnrosswvsu** [comment]
Removed permissions in feature and exported using secure_permissions.

Please check.

**Comment by johnrosswvsu** [comment]
@Luukyb Please check.

**Comment by johnrosswvsu** [comment]
I will also add a temporary update to removed session on first release.

**Comment by Luukyb** [comment]
We need to invite the visitor to create an account on the session page .... actually everyone would get a "Access denied"

**Comment by johnrosswvsu** [comment]
Adding: http://github.com/Luukyb/DrupalcampCebu2014/pull/57

**Comment by Luukyb** [comment]
Thanks !
