### ISSUE TITLE
Google analytics on live

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#37]
We need to setup google analytics on live.
Email address / account should be our drupalcebu@gmail.com. Look at the drupalcebu wiki for more details.
Reminder, This repo is open source, no connexion details on git !

**Comment by mtem27** [comment]
@Luukyb,

Please check, PR in https://github.com/Luukyb/DrupalcampCebu2014/pull/44. Thanks.

Tere

**Comment by mtem27** [comment]
To do:

Remove from profile. This should be installed only in live site.

**Comment by Luukyb** [comment]
Just need vince to change the key and it's all good.
