### ISSUE TITLE
Proposals view

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#38]
Pretty much a clone of our current speakers view. Except it should be displaying the proposals (sessions NOT accepted).
Same as for the featured speakers (6 items in the front page), then full details as a page.

**Comment by johnrosswvsu** [comment]
Working on this.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check.

Adding proposals Views.
Adding Proposals to the homepage.
Adding favorite flag for users to 'favorite up' proposed sessions.

https://github.com/Luukyb/DrupalcampCebu2014/pull/40

**Comment by Luukyb** [comment]
Merged. https://github.com/Luukyb/DrupalcampCebu2014/pull/40
Thanks JR.
BTW for your PR title, use the word ticket + a hastag. "Features proposals view. Ticket #38"
