### ISSUE TITLE
Price tag

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#51]
The early bird price has been decided !
Please include the price tag to pre-site and drupal theme
![screen shot 2014-09-24 at 14 59 26](https://cloud.githubusercontent.com/assets/1465207/4384595/14cd866e-43b9-11e4-8e60-1277724c2452.png)

**Comment by Luukyb** [comment]
This should be a link to the registration page.

**Comment by johnrosswvsu** [comment]
This is already in the work in this PR: https://github.com/Luukyb/DrupalcampCebu2014/pull/64

**Comment by johnrosswvsu** [comment]
This is already pointing to registration page, created through views.
