### ISSUE TITLE
Partners on sponsor page

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#60]
In the content type sponsor, add the boolean flag (checkbox ticked or not ticked) called "Partner".
In the sponsor page, add after the sponsors a list of the partners using the same kind of display.
The first partner we have is a "Community partner". This value "Community partner" should probably be added to the taxonomy "sponsor type".

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check:

Added feature flag.
Updated sponsors views.

https://github.com/Luukyb/DrupalcampCebu2014/pull/62
