### ISSUE TITLE
Theme the login buttons

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#61]
on /user page
![screen shot 2014-09-26 at 14 49 01](https://cloud.githubusercontent.com/assets/1465207/4416825/e6ff72c8-4549-11e4-9a03-cb9da44fa495.png)

**Comment by johnrosswvsu** [comment]
Hi @Luukyb 

Adds styling on the login toggle.

https://github.com/Luukyb/DrupalcampCebu2014/pull/63

**Comment by johnrosswvsu** [comment]
I also included this as well:

https://github.com/Luukyb/DrupalcampCebu2014/pull/64

For the registration link converting it to views.

**Comment by johnrosswvsu** [comment]
Price tag link is now referred to here: https://github.com/Luukyb/DrupalcampCebu2014/issues/51

**Comment by johnrosswvsu** [comment]
Add style on the title. "You are not logged in."

**Comment by johnrosswvsu** [comment]
@Luukyb 

http://screencast.com/t/GrVWtbGFuA
Please check:

Added style on the title. You are not logged in.

https://github.com/Luukyb/DrupalcampCebu2014/pull/68

**Comment by johnrosswvsu** [comment]
Closing.
