### ISSUE TITLE
Mailchimp on the footer

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#72]
Integrate the mailchimp form in the footer.

**Comment by mtem27** [comment]
@Luukyb , 

Should subscribe to mailchimp be added in the CONNECT section in footer?

**Comment by Luukyb** [comment]
@mtem27  Have a try after the sponsors, see how it looks like. thanks !

**Comment by mtem27** [comment]
@Luukyb 

Sorry, kind of confused, do you mean in this area? http://screencast.com/t/mS6gvBcP0

Thanks.

**Comment by mtem27** [comment]
@Luukyb ,

Please review here, https://github.com/Luukyb/DrupalcampCebu2014/pull/85, not yet themed

Thanks.

Tere

**Comment by Luukyb** [comment]
@mtem27 Thanks for your work. There was no need of a custom module here. A simple paste on the template page.tpl.php with css theming was ok, as the mailchimp form will be on every page (unless we have performance issues).
Issues fixed by @marychris
