### ISSUE TITLE
Speaker's space

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#74]
A place for speakers resources in the site.
- Powerpoint template for the camp
- Help on preparing the session
- Contact if they need help

A session is 45 minutes long, including 5 to 10 minutes Q&A.

**Comment by mtem27** [comment]
@Luukyb,

How should this work? Are these just basic pages to link to and power point template is a downloadable file?

Thanks.

**Comment by Luukyb** [comment]
This is low priority at the moment :)
