### ISSUE TITLE
Redundant Sponsors on sponsor page.

### ISSUE THREAD

**Issue by johnrosswvsu** [Luukyb/DrupalcampCebu2014#75]

**Comment by johnrosswvsu** [comment]
Hi @Luukyb,

Please check.

Removed redundancy of sponsors on sponsors page.

https://github.com/Luukyb/DrupalcampCebu2014/pull/77

**Comment by johnrosswvsu** [comment]
http://screencast.com/t/jPVEglklzyY

**Comment by Luukyb** [comment]
How did you fix it ?
I couldn't find an option "except" in context. Like : display the sponsor block in every page EXCEPT the sponsor page.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb 

the except option in context is using tilde ~ (~path)

I added a new condition for path.

I also created a new views display as block on suited for the page to include the accommodation partner.

**Comment by Luukyb** [comment]
haaa nice !! Thanks !

**Comment by Luukyb** [comment]
Merged
