### ISSUE TITLE
Anti Spam on registration

### ISSUE THREAD

**Issue by johnrosswvsu** [Luukyb/DrupalcampCebu2014#76]

**Comment by johnrosswvsu** [comment]
Hi @Luukyb

Installing mollom but config are not featurable.

Keys are added in the local settings php file.

(Need to be updated using drupalcampcebu@gmail.com email registrant.)

https://github.com/Luukyb/DrupalcampCebu2014/pull/79

**Comment by Luukyb** [comment]
Done already, using Honeypot

---

**Comment by johnrosswvsu** [comment]
Closing since this is not anymore needed.
