### ISSUE TITLE
All new users are displayed as "blocked"

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/DrupalcampCebu2014#90]

**Comment by Luukyb** [comment]
All the new users are "blocked", but they are real accounts. What changed ? What happened on these accounts ?

**Comment by johnrosswvsu** [comment]
We should traced who set this: http://2014.drupalcebu.org/admin/config/people/accounts

**Comment by johnrosswvsu** [comment]
As per https://github.com/Luukyb/DrupalcampCebu2014/commit/4d880830ff8d77579a9a29162374a61074382c53

The setting should be 1:

$strongarm->name = 'user_register';
$strongarm->value = '1';

Meaning the Visitors are allowed to register without approval.

But the current production setting as of the moment is set to 2.

Meaning Visitors are allowed to create accounts but admin approval is required.

**Comment by johnrosswvsu** [comment]
Hi @Luukyb 

I think you set the user_register to 2: https://github.com/Luukyb/DrupalcampCebu2014/commit/25475fcdbb7880b374c5aba86fad935f2bcff1fb when you updated and committed "Updated profile user with tshirt and food preference"

http://screencast.com/t/WdHetmf5P

Should we change this setting?

**Comment by johnrosswvsu** [comment]
For now I will activate real accounts because this is as what be the workflow for the moment based on the settings.

**Comment by johnrosswvsu** [comment]
I made a pr to change the settings: 

https://github.com/Luukyb/DrupalcampCebu2014/pull/91

**Comment by Luukyb** [comment]
I did change the value directly in prod, so the feature would have been overridden. It probably got reverted at some point in prod.

**Comment by Luukyb** [comment]
Merged, thanks JR !
